version: 2
jobs:
  build_windows:
    docker:
      - image: stefanscherer/node-windows:latest
    steps:
      - checkout
      - run: npm install --global yarn
      - run: yarn && yarn run publish
      - store_artifacts:
          path: /root/project/out

workflows:
  version: 2
  build:
    jobs:
      - build_windows